services:
  app:
    image: andreyvorobevaqa/samba-web-ui:latest
    container_name: samba-web-ui
    restart: unless-stopped
    environment:
      - JAVA_OPTS=-Xmx256m -Xms128m
      - SAMBA_HOST=${SAMBA_HOST:-localhost}
      - SAMBA_USER=${SAMBA_USER:-root}
      - SAMBA_PASSWORD=${SAMBA_PASSWORD:-}
    ports:
      - "8081:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge