version: '3.8'

services:
  samba-nas:
    build: .
    container_name: samba-web-ui
    restart: unless-stopped
    ports:
      # Web UI
      - "8080:8080"
      # Samba / SMB Ports
      - "445:445"
      - "139:139"
      # (Optional) External SSH. Internally used on :22
      # - "2222:22"
    volumes:
      # Mount your specific host directories here to expose via Samba
      - ./data:/mnt/samba
      # Keep smb.conf persisted globally
      - ./config:/etc/samba
    environment:
      - TZ=UTC
    privileged: true # Sometimes required for deep kernel chown/permissions matching
