[global]
    workgroup = WORKGROUP
    server string = Samba Web UI Appliance
    server role = standalone server
    security = user
    map to guest = Bad User
    passdb backend = tdbsam
    load printers = no
    disable netbios = yes
    smb ports = 445
