import { useState, useEffect } from "react";

export type Language = "ru" | "en";

export const translations = {
  en: {
    common: {
      cancel: "Cancel",
      save: "Save",
      create: "Create",
      add: "Add",
      delete: "Delete",
      remove: "Remove",
      confirm: "Confirm",
      actions: "Actions",
      members: "Members",
      root: "root"
    },
    sidebar: {
      dashboard: "Overview",
      shares: "Shares",
      users: "Users",
      groups: "Groups",
      settings: "Settings",
      logout: "Sign Out",
      server: "Server",
      user: "User",
      running: "Running",
      stopped: "Stopped",
      wait: "Wait..."
    },
    dashboard: {
      title: "System Overview",
      serviceStatus: "Service Status",
      startService: "Start Service",
      stop: "Stop",
      restart: "Restart",
      activeSessions: "Active Sessions",
      clients: "clients",
      openFiles: "Open Files",
      locked: "locked",
      noFilesInUse: "No files in use",
      storageExplorer: "Storage & Explorer",
      total: "Total",
      used: "Used",
      free: "Free",
      mount: "Mount",
      mkdir: "New Directory",
      dirEmpty: "Directory is empty",
      dirname: "dirname"
    },
    shares: {
      title: "Network Shares",
      newShare: "New Share",
      noShares: "No shares available",
      noSharesDesc: "Create your first directory to share over the network.",
      createShare: "Create Share",
      shareName: "Share Name",
      diskPath: "Disk Path",
      access: "Access",
      comment: "Comment",
      browseable: "Browseable",
      readOnly: "Read Only",
      guestOk: "Guest Ok",
      validUsers: "Valid Users / Access",
      validUsersHint: "Groups start with '@'. Comma separated.",
      externalGroups: "External Groups",
      localUsers: "Local Users",
      advOptions: "Advanced Options",
      writeList: "Write List",
      maxConn: "Max Connections",
      createMask: "Create Mask",
      dirMask: "Directory Mask",
      forceUser: "Force User",
      forceGroup: "Force Group",
      hostsAllow: "Hosts Allow",
      hostsDeny: "Hosts Deny",
      configure: "Configure",
      private: "PRIVATE"
    },
    users: {
      title: "System Users",
      addUser: "Add User",
      noUsers: "No users found",
      noUsersDesc: "You have no synchronized Samba users yet.",
      changePwd: "Change Password",
      username: "Username",
      fullName: "Full Name (Optional)",
      password: "Password",
      newPassword: "New Password",
      pwdDesc: "Set new SMB password for "
    },
    groups: {
      title: "System Groups",
      newGroup: "New Group",
      noGroups: "No OS Groups",
      posixGroup: "POSIX Group",
      emptyGroup: "Empty group",
      groupName: "Group Name",
      addToGroup: "Add to ",
      newOsGroup: "New OS Group"
    },
    config: {
      title: "Global Configuration",
      general: "General",
      network: "Network",
      security: "Security",
      workgroup: "Workgroup",
      netbiosName: "NetBIOS Name",
      serverString: "Server String",
      loadPrinters: "Load Printers",
      interfaces: "Interfaces (Listen IP/Eth)",
      bindInterfacesOnly: "Bind Interfaces Only",
      disableNetbios: "Disable NetBIOS",
      securityModel: "Security Model",
      mapToGuest: "Map To Guest",
      minProtocol: "Min Protocol",
      maxProtocol: "Max Protocol",
      defaults: "Reset Defaults",
      applyConfig: "Apply Config",
      saving: "Saving...",
      autoGenerated: "Auto-generated if empty",
      activeDirectory: "Active Directory",
      never: "Never",
      badUser: "Bad User",
      badPassword: "Bad Password"
    }
  },
  ru: {
    common: {
      cancel: "Отмена",
      save: "Сохранить",
      create: "Создать",
      add: "Добавить",
      delete: "Удалить",
      remove: "Исключить",
      confirm: "Подтвердить",
      actions: "Действия",
      members: "Участники",
      root: "корень"
    },
    sidebar: {
      dashboard: "Дашборд",
      shares: "Сетевые папки",
      users: "Пользователи",
      groups: "Группы ОС",
      settings: "Настройки",
      logout: "Выйти",
      server: "Сервер",
      user: "ОС Юзер",
      running: "Запущен",
      stopped: "Остановлен",
      wait: "Ожидание..."
    },
    dashboard: {
      title: "Обзор системы",
      serviceStatus: "Статус Samba",
      startService: "Запустить",
      stop: "Остановить",
      restart: "Перезапуск",
      activeSessions: "Активные сессии",
      clients: "клиентов",
      openFiles: "Открытые файлы",
      locked: "захвачено",
      noFilesInUse: "Нет открытых файлов",
      storageExplorer: "Диски и Файлы",
      total: "Всего",
      used: "Занято",
      free: "Свободно",
      mount: "Точка монтирования",
      mkdir: "Новая папка",
      dirEmpty: "Папка пуста",
      dirname: "имя_папки"
    },
    shares: {
      title: "Общие сетевые папки",
      newShare: "Добавить папку",
      noShares: "Нет общих папок",
      noSharesDesc: "Создайте свою первую сетевую папку (share).",
      createShare: "Создать папку",
      shareName: "Имя (Сетевое)",
      diskPath: "Путь на сервере",
      access: "Доступ",
      comment: "Описание (Комментарий)",
      browseable: "Видимость (Browseable)",
      readOnly: "Только чтение",
      guestOk: "Гостевой вход",
      validUsers: "Разрешенные пользователи",
      validUsersHint: "Группы начинаются с '@'. Разделять запятыми.",
      externalGroups: "Группы ОС",
      localUsers: "Локальные пользователи",
      advOptions: "Продвинутые параметры",
      writeList: "Право записи (write list)",
      maxConn: "Макс. подключений",
      createMask: "Маска новых файлов",
      dirMask: "Маска новых папок",
      forceUser: "Принуд. юзер",
      forceGroup: "Принуд. группа",
      hostsAllow: "Разрешенные IP",
      hostsDeny: "Запрещенные IP",
      configure: "Настроить",
      private: "ЧАСТНАЯ"
    },
    users: {
      title: "Пользователи Samba",
      addUser: "Новый пользователь",
      noUsers: "Пользователи не найдены",
      noUsersDesc: "Синхронизируйте системного юзера с базой Samba (smbpasswd).",
      changePwd: "Сменить пароль",
      username: "Логин (Username)",
      fullName: "Полное ФИО (опционально)",
      password: "Пароль Samba",
      newPassword: "Новый пароль",
      pwdDesc: "Задать новый SMB-пароль для "
    },
    groups: {
      title: "Группы Linux",
      newGroup: "Новая группа",
      noGroups: "Нет пользовательских групп",
      posixGroup: "Группа POSIX",
      emptyGroup: "Группа пуста",
      groupName: "Имя системной группы",
      addToGroup: "Добавление в ",
      newOsGroup: "Новая группа ОС"
    },
    config: {
      title: "Глобальная конфигурация",
      general: "Основные",
      network: "Сеть",
      security: "Безопасность",
      workgroup: "Рабочая группа",
      netbiosName: "NetBIOS Имя сервера",
      serverString: "Комментарий сервера",
      loadPrinters: "Загружать принтеры",
      interfaces: "Сетевые интерфейсы",
      bindInterfacesOnly: "Работать только на указанных (bind interfaces only)",
      disableNetbios: "Отключить NetBIOS",
      securityModel: "Модель безопасности",
      mapToGuest: "Маппинг гостей (map to guest)",
      minProtocol: "Мин. протокол",
      maxProtocol: "Макс. протокол",
      defaults: "Вернуть по умолчанию",
      applyConfig: "Применить",
      saving: "Сохранение...",
      autoGenerated: "Автогенерация, если пусто",
      activeDirectory: "Active Directory (ADS)",
      never: "Никогда (Never)",
      badUser: "Плохой юзер (Bad User)",
      badPassword: "Плохой пароль (Bad Password)"
    }
  }
};

let currentLang: Language = (localStorage.getItem("samba_lang") as Language) || "ru";
const listeners = new Set<(lang: Language) => void>();

export const setLanguage = (lang: Language) => {
  currentLang = lang;
  localStorage.setItem("samba_lang", lang);
  listeners.forEach(l => l(lang));
};

export const getLanguage = () => currentLang;

export const useTranslation = () => {
  const [lang, setLang] = useState<Language>(currentLang);
  
  useEffect(() => {
    listeners.add(setLang);
    return () => {
      listeners.delete(setLang);
    };
  }, []);

  const t = (key: string): string => {
    const keys = key.split(".");
    let res: any = translations[lang];
    for (const k of keys) {
      if (res === undefined) break;
      res = res[k];
    }
    return res !== undefined ? res : key;
  };

  return { t, lang, setLanguage };
};
