changelog:
  categories:
    - title: "Новые функции и возможности"
      labels:
        - "enhancement"
        - "feature"
      prefixes:
        - "feat:"
        - "feat("
        - "feat"

    - title: "Исправления ошибок"
      labels:
        - "bug"
        - "fix"
      prefixes:
        - "fix:"
        - "fix("
        - "fix"

    - title: "Архитектура и рефакторинг"
      labels:
        - "refactor"
      prefixes:
        - "refactor:"
        - "refactor("
        - "refactor"

    - title: "Пользовательский интерфейс (UI/UX)"
      labels:
        - "ui"
        - "style"
      prefixes:
        - "style:"
        - "style("
        - "ui:"
        - "ui("

    - title: "CI/CD, сборка и зависимости"
      labels:
        - "ci"
        - "chore"
        - "dependencies"
      prefixes:
        - "ci:"
        - "ci("
        - "chore:"
        - "chore("
        - "build:"
        - "build("

  # Исключаем из чейнджлога чисто служебные коммиты
  exclude:
    labels:
      - "ignore-for-release"
    prefixes:
      - "Merge branch"
      - "Merge pull request"